/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by customhbm2java", 0)}
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} abstract ${pojo.getDeclarationType()} Abstract${pojo.getDeclarationName()} extends com.acminds.acuteauto.persistence.BaseDTO ${pojo.getImplementsDeclaration()}