INSERT INTO COUNTRY( COUNTRY_ID, NAME, SYMBOL
) VALUES ( 1, 'UNITED STATES', 'USA'); 
 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
412, 'Armed Forces International', 'AE', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
413, 'Armed Forces Americas', 'AA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
414, 'Armed Forces Pacific', 'AP', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
340, 'Alaska', 'AK', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
341, 'Alabama', 'AL', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
342, 'Arkansas', 'AR', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
343, 'Arizona', 'AZ', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
344, 'California', 'CA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
345, 'Colorado', 'CO', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
346, 'Connecticut', 'CT', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
347, 'District Columbia', 'DC', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
348, 'Delaware', 'DE', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
349, 'Florida', 'FL', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
350, 'Georgia', 'GA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
351, 'Hawaii', 'HI', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
352, 'Iowa', 'IA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
353, 'Idaho', 'ID', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
354, 'Illinois', 'IL', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
355, 'Indiana', 'IN', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
356, 'Kansas', 'KS', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
357, 'Kentucky', 'KY', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
358, 'Louisiana', 'LA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
359, 'Massachusetts', 'MA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
360, 'Maryland', 'MD', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
361, 'Maine', 'ME', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
362, 'Michigan', 'MI', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
363, 'Minnesota', 'MN', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
364, 'Missouri', 'MO', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
365, 'Mississippi', 'MS', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
366, 'Montana', 'MT', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
367, 'North Carolina', 'NC', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
368, 'North Dakota', 'ND', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
369, 'Nebraska', 'NE', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
370, 'New Hampshire', 'NH', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
371, 'New Jersey', 'NJ', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
372, 'New Mexico', 'NM', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
373, 'Nevada', 'NV', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
374, 'New York', 'NY', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
375, 'Ohio', 'OH', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
376, 'Oklahoma', 'OK', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
377, 'Oregon', 'OR', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
378, 'Pennsylvania', 'PA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
379, 'Rhode Island', 'RI', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
380, 'South Carolina', 'SC', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
381, 'South Dakota', 'SD', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
382, 'Tennessee', 'TN', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
383, 'Texas', 'TX', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
384, 'Utah', 'UT', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
385, 'Virginia', 'VA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
386, 'Vermont', 'VT', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
387, 'Washington', 'WA', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
388, 'Wisconsin', 'WI', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
389, 'West Virginia', 'WV', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
390, 'Wyoming', 'WY', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
391, 'American Samoa', 'AS', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
392, 'Federated States Of Micronesia', 'FM', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
393, 'Guam', 'GU', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
394, 'Marshall Islands', 'MH', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
395, 'Northern Mariana Islands', 'MP', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
396, 'Palau', 'PW', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
397, 'Puerto Rico', 'PR', 1); 
INSERT INTO STATE( STATE_ID, NAME, SYMBOL, COUNTRY_ID ) VALUES ( 
398, 'US Virgin Islands', 'VI', 1); 

update STATE set name=upper(name);

COMMIT; 