/********************EXECUTE SEQUENCE 3********************/

/*************CONVERT EXISTING MYSQL TABLES TO INNODB TABLES TO SUPPORT *********
 *************RELATIONSHIPS AS THE NORMAL TABLES IN MYSQL DOES NOT SUPPORT ******
 *************RELATIONSHIPS. THIS IS NEEDED ONLY FOR NON INNODB MYSQL DATABASE***/
ALTER TABLE USER_INFO ENGINE=InnoDB;
ALTER TABLE CLIENT ENGINE=InnoDB;
ALTER TABLE COUNTRY ENGINE=InnoDB;
ALTER TABLE ENUM_TYPE ENGINE=InnoDB;
ALTER TABLE ENUM ENGINE=InnoDB;
ALTER TABLE LOCATION ENGINE=InnoDB;
ALTER TABLE PRIVILEGE ENGINE=InnoDB;
ALTER TABLE ROLE ENGINE=InnoDB;
ALTER TABLE AUDIT_LOG ENGINE=InnoDB;
ALTER TABLE RL_ROLE_PRIVILEGE ENGINE=InnoDB;
ALTER TABLE STATE ENGINE=InnoDB;

ALTER TABLE YEAR ENGINE=InnoDB;
ALTER TABLE MAKE ENGINE=InnoDB;
ALTER TABLE MODEL ENGINE=InnoDB;
ALTER TABLE STYLE ENGINE=InnoDB;
ALTER TABLE CATEGORY ENGINE=InnoDB;
ALTER TABLE VEHICLE ENGINE=InnoDB;
ALTER TABLE FEATURE_GROUP ENGINE=InnoDB;
ALTER TABLE FEATURE ENGINE=InnoDB;
ALTER TABLE IMAGE ENGINE=InnoDB;
ALTER TABLE ADVERTISEMENT ENGINE=InnoDB;
ALTER TABLE MILEAGE ENGINE=InnoDB;
ALTER TABLE LOAN_APPLICATION ENGINE=InnoDB;
ALTER TABLE APPLICANT ENGINE=InnoDB;
ALTER TABLE RESIDENCE ENGINE=InnoDB;
ALTER TABLE TRADEIN_INFO ENGINE=InnoDB;
ALTER TABLE EMPLOYMENT ENGINE=InnoDB;
ALTER TABLE ACCOUNT ENGINE=InnoDB;
ALTER TABLE INQUIRY ENGINE=InnoDB;
ALTER TABLE FIND_VEHICLE ENGINE=InnoDB;
ALTER TABLE TRASH_CAN ENGINE=InnoDB;

ALTER TABLE RL_VEHICLE_CATEGORY ENGINE=InnoDB;
ALTER TABLE RL_VEHICLE_FEATURE ENGINE=InnoDB;
ALTER TABLE RL_STYLE_FEATURE ENGINE=InnoDB;


