package com.acminds.acuteauto.persistence.dto;

// Generated Feb 26, 2012 11:28:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Advertisement generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractAdvertisement;

@ManagedBean(name = "advertisement")
@Entity
@Table(name = "ADVERTISEMENT", catalog = "carobar")
public class Advertisement extends AbstractAdvertisement {
	private static final long serialVersionUID = 1L;

}
