package com.acminds.acuteauto.persistence.dto;

// Generated May 13, 2012 8:10:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Applicant generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractApplicant;

@ManagedBean(name = "applicant")
@Entity
@Table(name = "APPLICANT")
public class Applicant extends AbstractApplicant {
	private static final long serialVersionUID = 1L;

}
