package com.acminds.acuteauto.persistence.dto;

// Generated Jun 28, 2012 7:41:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuditLog generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractAuditLog;

@ManagedBean(name = "auditLog")
@Entity
@Table(name = "AUDIT_LOG")
public class AuditLog extends AbstractAuditLog {
	private static final long serialVersionUID = 1L;

}
