package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Category generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractCategory;

@ManagedBean(name = "category")
@Entity
@Table(name = "CATEGORY")
public class Category extends AbstractCategory {
	private static final long serialVersionUID = 1L;
	
	private List<Vehicle> selectedVehicles;
	@Transient
	public List<Vehicle> getSelectedVehicles() {
		if(selectedVehicles == null)
			selectedVehicles = new ArrayList<Vehicle>(getVehicles());
		return selectedVehicles;
	}
	public void setSelectedVehicles(List<Vehicle> selectedVehicles) {
		this.selectedVehicles = selectedVehicles;
	}
	

}
