package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Client generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractClient;
import com.acminds.acuteauto.utils.EnumConstants.LocationType;

@ManagedBean(name = "client")
@Entity
@Table(name = "CLIENT")
public class Client extends AbstractClient {
	private static final long serialVersionUID = 1L;
	
	@Transient
	public Location getPrimaryLocation() {
		for(Location l:getLocations()) {
			if(LocationType.PRIMARY == l.getLocationType())
				return l;
		}
		return null;
	}

}
