package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Country generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractCountry;

@ManagedBean(name = "country")
@Entity
@Table(name = "COUNTRY")
public class Country extends AbstractCountry {
	private static final long serialVersionUID = 1L;

}
