package com.acminds.acuteauto.persistence.dto;

// Generated Feb 27, 2012 11:04:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnumType generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractEnumType;

@ManagedBean(name = "enumType")
@Entity
@Table(name = "ENUM_TYPE", catalog = "carobar")
public class EnumType extends AbstractEnumType {
	private static final long serialVersionUID = 1L;

}
