package com.acminds.acuteauto.persistence.dto;

// Generated Feb 26, 2012 11:28:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Feature generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractFeature;

@ManagedBean(name = "feature")
@Entity
@Table(name = "FEATURE", catalog = "carobar")
public class Feature extends AbstractFeature {
	private static final long serialVersionUID = 1L;

}
