package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * FeatureGroup generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractFeatureGroup;

@ManagedBean(name = "featureGroup")
@Entity
@Table(name = "FEATURE_GROUP")
public class FeatureGroup extends AbstractFeatureGroup {
	private static final long serialVersionUID = 1L;

	private boolean selected;
	@Transient
	public boolean isSelected() {
		return selected;
	}
	public void setSelected(boolean selected) {
		this.selected = selected;
	}
	
}
