package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FindVehicle generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractFindVehicle;

@ManagedBean(name = "findVehicle")
@Entity
@Table(name = "FIND_VEHICLE", catalog = "carobar")
public class FindVehicle extends AbstractFindVehicle {
	private static final long serialVersionUID = 1L;

}
