package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Image generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractImage;
import com.acminds.acuteauto.utils.EnumConstants.ImageType;
import com.acminds.acuteauto.utils.Utils;

@ManagedBean(name = "image")
@Entity
@Table(name = "IMAGE")
public class Image extends AbstractImage {
	private static final long serialVersionUID = 1L;
	private byte[] imageData;
	@Transient
	public byte[] getImageData() {
		return imageData;
	}
	public void setImageData(byte[] imageData) {
		this.imageData = imageData;
	}

	@Transient
	public String getRealLocation() {
		return Utils.getUserHome()+getImageLocation();
	}
	
	private boolean selectForDisplay;
	@Transient
	public boolean isSelectForDisplay() {
		if(getImageType()!=null && getImageType()==ImageType.PRIMARY)
			selectForDisplay = true;
		return selectForDisplay;
	}
	public void setSelectForDisplay(boolean selectForDisplay) {
		this.selectForDisplay = selectForDisplay;
		if(selectForDisplay)
			setImageType(ImageType.PRIMARY);
		else
			setImageType(null);
	}
	
	

}
