package com.acminds.acuteauto.persistence.dto;

// Generated Feb 27, 2012 11:04:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LoanApplication generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractLoanApplication;

@ManagedBean(name = "loanApplication")
@Entity
@Table(name = "LOAN_APPLICATION", catalog = "carobar")
public class LoanApplication extends AbstractLoanApplication {
	private static final long serialVersionUID = 1L;

}
