package com.acminds.acuteauto.persistence.dto;

// Generated Feb 27, 2012 11:04:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Location generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractLocation;

@ManagedBean(name = "location")
@Entity
@Table(name = "LOCATION", catalog = "carobar")
public class Location extends AbstractLocation {
	private static final long serialVersionUID = 1L;

}
