package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Location generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractLocation;
import com.acminds.acuteauto.utils.EnumConstants.LocationType;

@ManagedBean(name = "location")
@Entity
@Table(name = "LOCATION")
public class Location extends AbstractLocation {
	private static final long serialVersionUID = 1L;
	private StringBuilder addressForMap;
	@Transient
	public String getAddressForMap() {
		if(addressForMap == null) {
			addressForMap = new StringBuilder();			
			addressForMap.append(getAddress1())
			.append(" ")
			.append(getAddress2())
			.append(" ")
			.append(getCity())
			.append(" ")
			.append(getState())
			.append(" ")
			.append(getZip());
		}
		return addressForMap.toString();
	}
	@Transient
	public boolean isPrimary() {
		return (getLocationType() == LocationType.PRIMARY);
	}

}
