package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractModel;

@ManagedBean(name = "model")
@Entity
@Table(name = "MODEL")
public class Model extends AbstractModel {
	private static final long serialVersionUID = 1L;
	
	private List<Style> stylesForCatList;
	@Transient
	public List<Style> getStylesForCatList() {
		if(stylesForCatList==null)
			stylesForCatList = new ArrayList<Style>(getStyles());
		if(stylesForCatList.size()==0 || stylesForCatList.get(0).isPersistent()) {
			Style s = new Style();
			s.setModel(this);
			stylesForCatList.add(0, s);
		}
		return stylesForCatList;
	}

}
