package com.acminds.acuteauto.persistence.dto;

// Generated Feb 27, 2012 11:04:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Role generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractRole;

@ManagedBean(name = "role")
@Entity
@Table(name = "ROLE", catalog = "carobar")
public class Role extends AbstractRole {
	private static final long serialVersionUID = 1L;

}
