package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Role generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractRole;

@ManagedBean(name = "role")
@Entity
@Table(name = "ROLE")
public class Role extends AbstractRole {
	private static final long serialVersionUID = 1L;
	
	private List<Privilege> selectedPrivs;
	@Transient
	public List<Privilege> getSelectedPrivs() {
		return selectedPrivs;
	}
	public void setSelectedPrivs(List<Privilege> selectedPrivs) {
		this.selectedPrivs = selectedPrivs;
	}
	

}
