package com.acminds.acuteauto.persistence.dto;

// Generated Feb 29, 2012 11:25:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Style generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractStyle;

@ManagedBean(name = "style")
@Entity
@Table(name = "STYLE")
public class Style extends AbstractStyle {
	private static final long serialVersionUID = 1L;

}
