package com.acminds.acuteauto.persistence.dto;

// Generated May 13, 2012 8:10:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TradeinInfo generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractTradeinInfo;

@ManagedBean(name = "tradeinInfo")
@Entity
@Table(name = "TRADEIN_INFO")
public class TradeinInfo extends AbstractTradeinInfo {
	private static final long serialVersionUID = 1L;

}
