package com.acminds.acuteauto.persistence.dto;

// Generated Jun 28, 2012 7:41:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TrashCan generated by customhbm2java
 */
import javax.faces.bean.ManagedBean;

import com.acminds.acuteauto.persistence.entities.AbstractTrashCan;

@ManagedBean(name = "trashCan")
@Entity
@Table(name = "TRASH_CAN")
public class TrashCan extends AbstractTrashCan {
	private static final long serialVersionUID = 1L;

}
