package com.acminds.acuteauto.persistence.entities;

// Generated Mar 3, 2012 9:48:22 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import com.acminds.acuteauto.persistence.dto.*;

/**
 * Enum generated by customhbm2java
 */
@MappedSuperclass
public abstract class AbstractEnum extends
		com.acminds.acuteauto.persistence.BaseDTO implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer enumId;
	private EnumType enumType;
	private String enumValue;
	private String shortDesc;
	private String longDesc;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ENUM_ID", unique = true, nullable = false)
	public Integer getEnumId() {
		return this.enumId;
	}

	public void setEnumId(Integer enumId) {
		this.enumId = enumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENUM_TYPE_ID", nullable = false)
	public EnumType getEnumType() {
		return this.enumType;
	}

	public void setEnumType(EnumType enumType) {
		this.enumType = enumType;
	}

	@Column(name = "ENUM_VALUE", nullable = false, length = 60)
	public String getEnumValue() {
		return this.enumValue;
	}

	public void setEnumValue(String enumValue) {
		this.enumValue = enumValue;
	}

	@Column(name = "SHORT_DESC", length = 100)
	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	@Column(name = "LONG_DESC", length = 200)
	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

}
