package com.acminds.acuteauto.persistence.entities;

// Generated May 13, 2012 8:21:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import com.acminds.acuteauto.persistence.dto.*;

/**
 * FindVehicle generated by customhbm2java
 */
@MappedSuperclass
public abstract class AbstractFindVehicle extends
		com.acminds.acuteauto.persistence.BaseDTO implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer findVehicleId;
	private Inquiry inquiry;
	private Model model;
	private Style style;
	private Integer vehicleType;
	private Integer mileage;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FIND_VEHICLE_ID", unique = true, nullable = false)
	public Integer getFindVehicleId() {
		return this.findVehicleId;
	}

	public void setFindVehicleId(Integer findVehicleId) {
		this.findVehicleId = findVehicleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INQUIRY_ID", nullable = false)
	public Inquiry getInquiry() {
		return this.inquiry;
	}

	public void setInquiry(Inquiry inquiry) {
		this.inquiry = inquiry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODEL_ID")
	public Model getModel() {
		return this.model;
	}

	public void setModel(Model model) {
		this.model = model;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STYLE_ID")
	public Style getStyle() {
		return this.style;
	}

	public void setStyle(Style style) {
		this.style = style;
	}

	@Column(name = "VEHICLE_TYPE")
	public Integer getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(Integer vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Column(name = "MILEAGE")
	public Integer getMileage() {
		return this.mileage;
	}

	public void setMileage(Integer mileage) {
		this.mileage = mileage;
	}

}
