package com.acminds.acuteauto.persistence.entities;

// Generated Feb 26, 2012 11:32:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;

import com.acminds.acuteauto.persistence.dto.Enum;

/**
 * EnumType generated by customhbm2java
 */
@MappedSuperclass
public abstract class AbstractEnumType extends
		com.acminds.acuteauto.persistence.BaseDTO implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer enumTypeId;
	private String codeName;
	private String shortDesc;
	private String longDesc;
	private List<Enum> enums = new ArrayList<Enum>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ENUM_TYPE_ID", unique = true, nullable = false)
	public Integer getEnumTypeId() {
		return this.enumTypeId;
	}

	public void setEnumTypeId(Integer enumTypeId) {
		this.enumTypeId = enumTypeId;
	}

	@Column(name = "CODE_NAME", nullable = false, length = 60)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "SHORT_DESC", length = 100)
	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	@Column(name = "LONG_DESC", length = 200)
	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enumType")
	public List<Enum> getEnums() {
		return this.enums;
	}

	public void setEnums(List<Enum> enums) {
		this.enums = enums;
	}

}
